services:
  mysql:
    image: mysql:8.0
    container_name: doodle_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: qlsv
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - default

  phpmyadmin:
    container_name: doodle_pma
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=10
      - PMA_HOST=mysql
      - PMA_USER=user
      - PMA_PASSWORD=password
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - default

  # minio:
  #   image: minio/minio:RELEASE.2022-10-08T20-11-00Z
  #   command: server /data --console-address ":9001"
  #   restart: unless-stopped
  #   ports:
  #     - 9001:9001
  #     - 9000:9000
  #   environment:
  #     MINIO_ROOT_USER: minio
  #     MINIO_ROOT_PASSWORD: miniopass
  #   volumes:
  #     - ./docker/minio:/data
  #   networks:
  #     - default

networks:
  default:
    driver: bridge